# Generated by Django 3.0.4 on 2020-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IC_num', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '工资情况',
            },
        ),
    ]
