# Generated by Django 3.0.4 on 2020-04-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('IC_num', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '用户身份信息',
            },
        ),
    ]
