# Generated by Django 3.0.5 on 2020-05-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hlpprivateckey'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLP_otherPrivatecKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Deta', models.TextField()),
                ('A', models.TextField()),
                ('B', models.TextField()),
                ('N', models.IntegerField()),
                ('mods', models.IntegerField()),
                ('q', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'HLP_other私钥',
            },
        ),
        migrations.CreateModel(
            name='PaillierPrivatecKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g', models.TextField()),
                ('lamda', models.TextField()),
                ('n', models.TextField()),
                ('u', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Paillier私钥',
            },
        ),
    ]
