# Generated by Django 3.0.5 on 2020-05-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200406_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLPPublicKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('N', models.IntegerField()),
                ('ns', models.IntegerField()),
                ('mods', models.IntegerField()),
                ('Mhard', models.TextField()),
                ('Msoft', models.TextField()),
                ('random_numbers', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'HLP公钥',
            },
        ),
    ]
