# Generated by Django 3.0.5 on 2020-05-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hlppublickey'),
    ]

    operations = [
        migrations.CreateModel(
            name='En_Algorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('normal', models.IntegerField()),
                ('plus', models.IntegerField()),
                ('multiply', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '当前密钥',
            },
        ),
    ]
