# Generated by Django 3.0.5 on 2020-05-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_en_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLP_otherPublicKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('N', models.IntegerField()),
                ('ns', models.IntegerField()),
                ('mods', models.IntegerField()),
                ('Mhard', models.TextField()),
                ('Msoft', models.TextField()),
                ('random_numbers', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'HLP_other公钥',
            },
        ),
        migrations.CreateModel(
            name='PaillierPublicKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('r', models.TextField()),
                ('n', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Paillier公钥',
            },
        ),
    ]
